# Archivo de configuración de dependencias

[package]
name = "wasm_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.5", features = ["csr"] }
log = "0.4"
web-sys = { version = "0.3", features = ["console"] }
